export interface Agency {
  id: string;
  name: string;
  shortName: string;
  letter: string;
  logo?: string;       // filename in /logos/ — if set, shown instead of letter SVG
  primaryColor: string;
  darkColor: string;
  lightBg: string;
  phone: string;
  claimsPhone: string;
  website: string;
  address: string;
  pools: string[];
}

export const agencies: Agency[] = [
  {
    id: 'farmers',
    name: 'FARMERS INSURANCE',
    shortName: 'Farmers',
    letter: 'F',
    logo: 'farmers.png',
    primaryColor: '#006B49',
    darkColor: '#004D35',
    lightBg: '#f4f9f7',
    phone: '1-800-438-6461',
    claimsPhone: '1-800-435-7764',
    website: 'www.farmers.com',
    address: 'P.O. BOX 5324, LOS ANGELES, CA 90096-5324',
    pools: [
      'Farmers Insurance Exchange',
      'Fire Insurance Exchange',
      'Truck Insurance Exchange',
      'Mid-Century Insurance Company',
      'Bristol West Insurance Company',
      'Foremost Insurance Company',
    ],
  },
  {
    id: 'statefarm',
    name: 'STATE FARM INSURANCE',
    shortName: 'State Farm',
    letter: 'SF',
    logo: 'state_farm.svg',
    primaryColor: '#CC0000',
    darkColor: '#990000',
    lightBg: '#fff5f5',
    phone: '1-800-782-8332',
    claimsPhone: '1-800-732-5246',
    website: 'www.statefarm.com',
    address: 'ONE STATE FARM PLAZA, BLOOMINGTON, IL 61710',
    pools: [
      'State Farm Mutual Automobile Insurance Company',
      'State Farm Fire and Casualty Company',
      'State Farm General Insurance Company',
      'State Farm County Mutual Insurance Company of Texas',
    ],
  },
  {
    id: 'allstate',
    name: 'ALLSTATE INSURANCE',
    shortName: 'Allstate',
    letter: 'A',
    logo: 'allstate.svg',
    primaryColor: '#0047BA',
    darkColor: '#003490',
    lightBg: '#f0f4ff',
    phone: '1-800-255-7828',
    claimsPhone: '1-800-255-7828',
    website: 'www.allstate.com',
    address: '2775 SANDERS RD, NORTHBROOK, IL 60062',
    pools: [
      'Allstate Insurance Company',
      'Allstate Indemnity Company',
      'Allstate Property and Casualty Insurance Company',
      'Allstate Fire and Casualty Insurance Company',
      'National General Insurance Company',
    ],
  },
  {
    id: 'progressive',
    name: 'PROGRESSIVE INSURANCE',
    shortName: 'Progressive',
    letter: 'P',
    logo: 'progressive.svg',
    primaryColor: '#0071CE',
    darkColor: '#00559A',
    lightBg: '#f0f7ff',
    phone: '1-800-776-4737',
    claimsPhone: '1-800-274-4499',
    website: 'www.progressive.com',
    address: '6300 WILSON MILLS RD, MAYFIELD VILLAGE, OH 44143',
    pools: [
      'Progressive Casualty Insurance Company',
      'Progressive Classic Insurance Company',
      'Progressive Advanced Insurance Company',
      'Progressive Direct Insurance Company',
      'Progressive Northern Insurance Company',
    ],
  },
  {
    id: 'geico',
    name: 'GEICO INSURANCE',
    shortName: 'GEICO',
    letter: 'G',
    logo: 'geico.png',
    primaryColor: '#004C97',
    darkColor: '#003770',
    lightBg: '#f0f5ff',
    phone: '1-800-841-3000',
    claimsPhone: '1-800-841-3000',
    website: 'www.geico.com',
    address: 'ONE GEICO PLAZA, BETHESDA, MD 20810',
    pools: [
      'Government Employees Insurance Company',
      'GEICO Casualty Company',
      'GEICO Indemnity Company',
      'GEICO General Insurance Company',
    ],
  },
  {
    id: 'libertymutual',
    name: 'LIBERTY MUTUAL INSURANCE',
    shortName: 'Liberty Mutual',
    letter: 'LM',
    logo: 'liberty_mutual.png',
    primaryColor: '#B7232C',
    darkColor: '#8B1A21',
    lightBg: '#fff5f5',
    phone: '1-800-290-7933',
    claimsPhone: '1-800-225-2467',
    website: 'www.libertymutual.com',
    address: '175 BERKELEY ST, BOSTON, MA 02116',
    pools: [
      'Liberty Mutual Fire Insurance Company',
      'LM Insurance Corporation',
      'Liberty Insurance Corporation',
      'Liberty Mutual Personal Insurance Company',
      'Employers Insurance Company of Wausau',
    ],
  },
  {
    id: 'nationwide',
    name: 'NATIONWIDE INSURANCE',
    shortName: 'Nationwide',
    letter: 'N',
    logo: 'nationwide.png',
    primaryColor: '#0067B1',
    darkColor: '#004E88',
    lightBg: '#f0f6ff',
    phone: '1-877-669-6877',
    claimsPhone: '1-800-421-3535',
    website: 'www.nationwide.com',
    address: 'ONE NATIONWIDE PLAZA, COLUMBUS, OH 43215',
    pools: [
      'Nationwide Mutual Insurance Company',
      'Allied Property & Casualty Insurance Company',
      'Nationwide Property & Casualty Insurance Company',
      'Nationwide General Insurance Company',
      'Titan Insurance Company',
    ],
  },
  {
    id: 'amfam',
    name: 'AMERICAN FAMILY INSURANCE',
    shortName: 'AmFam',
    letter: 'AF',
    logo: 'american_family.svg',
    primaryColor: '#CC2033',
    darkColor: '#991827',
    lightBg: '#fff5f5',
    phone: '1-800-692-6326',
    claimsPhone: '1-800-374-1111',
    website: 'www.amfam.com',
    address: '6000 AMERICAN PKWY, MADISON, WI 53783',
    pools: [
      'American Family Mutual Insurance Company, S.I.',
      'American Family Insurance Company',
      'American Standard Insurance Company of Wisconsin',
      'American Standard Insurance Company of Ohio',
      'Midvale Indemnity Company',
    ],
  },
  {
    id: 'travelers',
    name: 'TRAVELERS INSURANCE',
    shortName: 'Travelers',
    letter: 'T',
    logo: 'travelers.svg',
    primaryColor: '#C8102E',
    darkColor: '#96001E',
    lightBg: '#fff5f5',
    phone: '1-800-842-5075',
    claimsPhone: '1-800-252-4633',
    website: 'www.travelers.com',
    address: '485 LEXINGTON AVE, NEW YORK, NY 10017',
    pools: [
      'Travelers Property Casualty Company of America',
      'Travelers Casualty and Surety Company',
      'The Travelers Indemnity Company',
      'Travelers Home and Marine Insurance Company',
      'St. Paul Fire and Marine Insurance Company',
    ],
  },
  {
    id: 'aaa',
    name: 'AAA INSURANCE',
    shortName: 'AAA',
    letter: 'AAA',
    logo: 'aaa.svg',
    primaryColor: '#003087',
    darkColor: '#001F5C',
    lightBg: '#f0f3ff',
    phone: '1-800-222-4357',
    claimsPhone: '1-800-222-4357',
    website: 'www.aaa.com',
    address: '1000 AAA DR, HEATHROW, FL 32746',
    pools: [
      'AAA Northern California, Nevada & Utah Insurance Exchange',
      'CSAA Insurance Exchange',
      'AAA Mid-Atlantic Insurance Company',
      'AAA Life Insurance Company',
      'Automobile Club of Southern California',
    ],
  },
  {
    id: 'usaa',
    name: 'USAA INSURANCE',
    shortName: 'USAA',
    letter: 'U',
    logo: 'usaa.svg',
    primaryColor: '#005A9C',
    darkColor: '#003D6B',
    lightBg: '#f0f5ff',
    phone: '1-800-531-8722',
    claimsPhone: '1-800-531-8722',
    website: 'www.usaa.com',
    address: '9800 FREDERICKSBURG RD, SAN ANTONIO, TX 78288',
    pools: [
      'USAA Casualty Insurance Company',
      'USAA General Indemnity Company',
      'Garrison Property and Casualty Insurance Company',
      'United Services Automobile Association',
    ],
  },
];

export const defaultAgency = agencies[0];
